# Generated by Django 6.0.2 on 2026-04-17 20:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photo_upload_to, validators=[accounts.models.validate_profile_photo_size, accounts.models.validate_profile_photo_extension]),
        ),
    ]
