# Generated by Django 6.0.2 on 2026-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_setup_done',
            field=models.BooleanField(default=False),
        ),
    ]
