# Generated by Django 6.0.2 on 2026-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sync_pending_with_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
