<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-27 14:30

import django.db.models.deletion
=======
# Generated by Django 6.0.2 on 2026-04-02 19:39

import django.db.models.deletion
import uuid
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
                ('model', models.CharField(max_length=120)),
                ('total_seats', models.PositiveIntegerField()),
                ('number_plate', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('iata_code', models.CharField(blank=True, default='', max_length=3)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20, unique=True)),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=20, unique=True)),
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_type', models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], default='ONE_WAY', max_length=20)),
                ('stops', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='core.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('confirmation_code', models.CharField(max_length=20, unique=True)),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('ONBOARD', 'On Board')], default='PENDING', max_length=20)),
                ('confirmation_code', models.CharField(max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Agent or staff who created this booking on behalf of the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_bookings', to=settings.AUTH_USER_MODEL)),
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('KID', 'Kid')], default='ADULT', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, default='', max_length=50)),
                ('phone_area_code', models.CharField(default='+254', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='core.booking')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('CARD', 'Credit Card')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='BoardingPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(blank=True, max_length=50)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('booking_status', models.CharField(blank=True, max_length=20)),
                ('already_onboard', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('boarding_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='core.boardingpass')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
                ('seat_number', models.CharField(max_length=10)),
                ('flight_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.aircraft')),
            ],
            options={
                'unique_together': {('aircraft', 'seat_number')},
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.seat')),
            ],
=======
        migrations.AddField(
            model_name='boardingpass',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='core.seat'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('CARD', 'Credit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('PESAPAL', 'Pesapal')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_detail', models.CharField(blank=True, help_text='Phone (M-Pesa), email (PayPal), masked card (Card), bank ref (Bank Transfer)', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('booking', 'provider'), name='unique_booking_payment')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('booking_create', 'Booking Created'), ('booking_cancel', 'Booking Cancelled'), ('payment', 'Payment Processed'), ('api_access', 'API Access'), ('admin_action', 'Admin Action'), ('file_upload', 'File Upload'), ('other', 'Other Action')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_c382a9_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_userac_ip_addr_146c68_idx'), models.Index(fields=['action', '-timestamp'], name='core_userac_action_8b7099_idx')],
            },
>>>>>>> 9007297460809f07bfaa364ef37dd6359fbbe48b
        ),
    ]
