# Generated by Django 6.0.2 on 2026-02-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardingpass',
            name='flight',
        ),
    ]
