# Generated by Django 6.0.2 on 2026-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_blocked', 'Login Blocked - IP Risk'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('booking_create', 'Booking Created'), ('booking_cancel', 'Booking Cancelled'), ('payment', 'Payment Processed'), ('api_access', 'API Access'), ('admin_action', 'Admin Action'), ('file_upload', 'File Upload'), ('other', 'Other Action')], max_length=50),
        ),
    ]
