# Generated by Django 6.0.2 on 2026-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stopover_city',
            field=models.CharField(blank=True, help_text='Selected stopover city for VIA flights', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='route_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('VIA', 'Via')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='via_cities',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of intermediate cities for VIA flights'),
        ),
    ]
