# Generated by Django 6.0.2 on 2026-04-17 19:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_stopover_city_flight_route_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpass',
            name='passenger_photo',
            field=models.ImageField(blank=True, help_text='Passenger photo for boarding verification (required for adults & children 4+)', null=True, upload_to=core.models.passenger_photo_upload_to, validators=[core.models.validate_passenger_photo_size, core.models.validate_passenger_photo_extension]),
        ),
    ]
