# Generated by Django 6.0.2 on 2026-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_passenger_photo_to_boarding_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
