# Generated by Django 6.0.2 on 2026-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_additional_data_to_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='action',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
