# Generated by Django 6.0.2 on 2026-02-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpass',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
