# Generated by Django 6.0.2 on 2026-02-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boardingpass_is_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('CARD', 'Credit Card'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20),
        ),
    ]
