# Generated by Django 6.0.2 on 2026-02-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_bank_transfer_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_detail',
            field=models.CharField(blank=True, help_text='Phone (M-Pesa), email (PayPal), masked card (Card), bank ref (Bank Transfer)', max_length=255, null=True),
        ),
    ]
