# Generated by Django 4.2.27 on 2026-02-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_add_payment_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('booking_create', 'Booking Created'), ('booking_cancel', 'Booking Cancelled'), ('payment', 'Payment Processed'), ('api_access', 'API Access'), ('admin_action', 'Admin Action'), ('file_upload', 'File Upload'), ('other', 'Other Action')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_c382a9_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_userac_ip_addr_146c68_idx'), models.Index(fields=['action', '-timestamp'], name='core_userac_action_8b7099_idx')],
            },
        ),
    ]
