# Generated by Django 6.0.2 on 2026-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('CARD', 'Credit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('PESAPAL', 'Pesapal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider_reference',), name='unique_provider_reference'),
        ),
    ]
