# Generated by Django 6.0.2 on 2026-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_payment_provider_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_provider_reference',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('booking', 'provider'), name='unique_booking_payment'),
        ),
    ]
